start cmd.exe /k "cd C:\Program Files\MongoDB\Server\6.0\bin && mongod.exe"
start cmd.exe /k "cd C:\Users\Alex\ProyectosGit\api-rest-node && npm start"
start cmd.exe /k "cd C:\Users\Alex\ProyectosGit\master-react\15-proyecto3 && npm run dev"
start "C:\Users\Alex\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\MongoDB Inc\MongoDBCompass.exe"
start "C:\Users\Alex\AppData\Local\Postman\Postman.exe"